### ISSUE TITLE
Debe haber por lo menos una etiqueta <img> en la página

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyecto2023-diaz-otanez-novillo-s-s#7]

**Comment by Hugodiazo** [comment]
ok, se agrego etiqueta img en el footer

**Comment by edme88** [comment]
La imagen se ve mal escalada
![imagen](https://github.com/UCC-LabCompu2/proyecto2023-diaz-otanez-novillo-s-s/assets/8345007/8000d882-fa92-40e7-941a-88521719561c)
